export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_SOCIAL_LOGIN_REQUEST = 'USER_SOCIAL_LOGIN_REQUEST'
export const USER_SOCIAL_LOGIN_SUCCESS = 'USER_SOCIAL_LOGIN_SUCCESS'
export const USER_SOCIAL_LOGIN_FAIL = 'USER_GOOGLE_LOGIN_FAIL'


export const USER_REGISTRATION_REQUEST = 'USER_REGISTRATION_REQUEST'
export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS'
export const USER_REGISTRATION_FAIL = 'USER_REGISTRATION_FAIL'

export const USER_SOCIAL_REGISTRATION_REQUEST = 'USER_SOCIAL_REGISTRATION_REQUEST'
export const USER_SOCIAL_REGISTRATION_SUCCESS = 'USER_SOCIAL_REGISTRATION_SUCCESS'
export const USER_SOCIAL_REGISTRATION_FAIL = 'USER_GOOGLE_REGISTRATION_FAIL'